# Generated by Django 6.0.1 on 2026-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_partnertier_delete_partnership_partner_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Exodus Global', max_length=255)),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('history', models.TextField()),
                ('email_contact', models.EmailField(max_length=254)),
                ('phone_contact', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Ministry Info',
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='event_date',
        ),
    ]
